
###############################################################################
#
# Inclusive Makefile for the bfns_ctl module.
#
# Autogenerated 2014-11-19 17:41:03.496269
#
###############################################################################
bfns_ctl_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

