
###############################################################################
#
# Inclusive Makefile for the bfns_common_utest module.
#
# Autogenerated 2014-11-19 18:29:22.489263
#
###############################################################################
bfns_common_utest_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

